name: Master Branch
on:
  push:
    branches:
      - 'master'
jobs:
  test:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Maven build
        run: mvn clean install -DSkipTest